import { ColorScheme } from '@/hooks/useTheme';
import { StyleSheet } from 'react-native';

export const createHomeStyles = (colors: ColorScheme) => {
  const styles = StyleSheet.create({
    container: {
      flex: 1,
    },
    safeArea: {
      flex: 1,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    loadingText: {
      marginTop: 20,
      fontSize: 16,
      fontWeight: '600',
      color: colors.text,
      opacity: 0.7,
      letterSpacing: 0.5,
    },
    header: {
      paddingHorizontal: 24,
      paddingTop: 32,
      paddingBottom: 16,
    },
    titleContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 20,
    },
    iconContainer: {
      width: 48,
      height: 48,
      borderRadius: 14,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 16,
      shadowOffset: { width: 2, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 6,
      elevation: 3,
    },
    titleTextContainer: {
      flex: 1,
    },
    title: {
      fontSize: 28,
      fontWeight: '800',
      letterSpacing: -0.3,
      marginBottom: 2,
      color: colors.text,
    },
    subtitle: {
      fontSize: 15,
      fontWeight: '500',
      color: colors.textMuted,
      opacity: 0.8,
      letterSpacing: 0.2,
    },
    progressContainer: {
      marginTop: 16,
    },
    progressBarContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    progressBar: {
      flex: 1,
      height: 6,
      borderRadius: 3,
      overflow: 'hidden',
      backgroundColor: colors.border + '20',
    },
    progressFill: {
      height: '100%',
      borderRadius: 3,
    },
    progressText: {
      fontSize: 14,
      fontWeight: '700',
      minWidth: 36,
      textAlign: 'right',
      color: colors.success,
      letterSpacing: 0.3,
    },
    inputSection: {
      paddingHorizontal: 24,
      paddingBottom: 16,
    },
    inputWrapper: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      gap: 12,
    },
    input: {
      flex: 1,
      borderWidth: 1,
      borderRadius: 14,
      paddingHorizontal: 18,
      paddingVertical: 14,
      fontSize: 15,
      maxHeight: 120,
      fontWeight: '500',
      backgroundColor: colors.backgrounds.input,
      borderColor: colors.border,
      color: colors.text,
    },
    inputFocused: {
      borderColor: colors.primary,
      backgroundColor: colors.backgrounds.input + 'f0',
      shadowColor: colors.primary,
      shadowOpacity: 0.15,
      shadowRadius: 6,
    },
    addButton: {
      width: 48,
      height: 48,
      borderRadius: 14,
      justifyContent: 'center',
      alignItems: 'center',
      // Floating button effect
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 6,
      transform: [{ translateY: -2 }],
    },
    addButtonDisabled: {
      opacity: 0.5,
      transform: [{ translateY: 0 }],
      shadowOpacity: 0.1,
    },
    todoList: {
      flex: 1,
    },
    todoListContent: {
      paddingHorizontal: 24,
      paddingBottom: 100,
    },
    emptyListContainer: {
      flexGrow: 1,
      justifyContent: 'center',
    },
    todoItemWrapper: {
      marginVertical: 8,
    },
    todoItem: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      padding: 16,
      borderRadius: 14,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 8,
      elevation: 2,
    },
    checkbox: {
      marginRight: 16,
      marginTop: 1,
    },
    checkboxInner: {
      width: 26,
      height: 26,
      borderRadius: 13,
      borderWidth: 2,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: colors.success,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0,
      shadowRadius: 4,
    },
    checkboxChecked: {
      shadowOpacity: 0.4,
    },
    todoTextContainer: {
      flex: 1,
    },
    todoText: {
      fontSize: 15,
      lineHeight: 21,
      fontWeight: '500',
      marginBottom: 12,
      color: colors.text,
      letterSpacing: 0.1,
    },
    todoActions: {
      flexDirection: 'row',
      gap: 8,
      marginTop: -4,
    },
    actionButton: {
      width: 34,
      height: 34,
      borderRadius: 10,
      justifyContent: 'center',
      alignItems: 'center',
      shadowOffset: { width: 0, height: 1 },
      shadowRadius: 2,
    },
    editContainer: {
      flex: 1,
    },
    editInput: {
      borderWidth: 1,
      borderRadius: 12,
      paddingHorizontal: 16,
      paddingVertical: 12,
      fontSize: 15,
      fontWeight: '500',
      marginBottom: 12,
      backgroundColor: colors.backgrounds.editInput,
      borderColor: colors.primary + '80',
      color: colors.text,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0,
      shadowRadius: 4,
    },
    editInputFocused: {
      shadowOpacity: 0.15,
      borderColor: colors.primary,
    },
    editButtons: {
      flexDirection: 'row',
      gap: 8,
    },
    editButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 10,
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.2,
      shadowRadius: 2,
    },
    editButtonText: {
      color: '#ffffff',
      fontSize: 13,
      fontWeight: '600',
      letterSpacing: 0.2,
    },
    emptyContainer: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 80,
    },
    emptyIconContainer: {
      width: 90,
      height: 90,
      borderRadius: 45,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 20,
      backgroundColor: colors.primary + '08',
      // Soft glow
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
    },
    emptyText: {
      fontSize: 20,
      fontWeight: '700',
      marginBottom: 8,
      color: colors.text,
      textAlign: 'center',
      letterSpacing: 0.3,
    },
    emptySubtext: {
      fontSize: 14,
      textAlign: 'center',
      paddingHorizontal: 40,
      lineHeight: 21,
      color: colors.textMuted,
      opacity: 0.7,
      letterSpacing: 0.2,
    },
  });

  return styles;
};
